version: '3.4'

volumes:
  postgres-data:

networks:
  net:

services:

  # PG
  postgres:
    container_name: postgres
    image: postgres:13.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - net

